#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries (v1.5)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
    with:
      duckdb_version: v1.5-variegata
      ci_tools_version: v1.5-variegata
      extension_name: tarfs

  duckdb-stable-build:
    name: Build extension binaries (v1.4)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      duckdb_version: v1.4-andium
      ci_tools_version: v1.4-andium
      extension_name: tarfs

  duckdb-next-deploy:
    name: Deploy extension binaries (v1.5)
    needs: duckdb-next-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v1.5-variegata
      ci_tools_version: v1.5-variegata
      extension_name: tarfs
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}

  duckdb-stable-deploy:
    name: Deploy extension binaries (v1.4)
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v1.4-andium
      ci_tools_version: v1.4-andium
      extension_name: tarfs
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
